# Generated by Django 4.1.4 on 2022-12-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_categoria_pergunta_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sub_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='sub_categoria',
            field=models.ManyToManyField(to='enquete.sub_categoria'),
        ),
    ]
